import HomeCategory from "./HomeCategory";

const meta = {
  component: HomeCategory,
};

export default meta;

export const Default = {
  args: {
    playlists: [
      [
        {
          added_at: "2015-01-15T12:39:22Z",
          added_by: {
            external_urls: {
              spotify: "https://open.spotify.com/user/jmperezperez",
            },
            href: "https://api.spotify.com/v1/users/jmperezperez",
            id: "jmperezperez",
            type: "user",
            uri: "spotify:user:jmperezperez",
          },
          is_local: false,
          track: {
            album: {
              album_type: "compilation",
              total_tracks: 20,
              available_markets: [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
              ],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/2pANdqPvxInB0YvcDiw4ko",
              },
              href: "https://api.spotify.com/v1/albums/2pANdqPvxInB0YvcDiw4ko",
              id: "2pANdqPvxInB0YvcDiw4ko",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273ce6d0eef0c1ce77e5f95bbbc",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02ce6d0eef0c1ce77e5f95bbbc",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851ce6d0eef0c1ce77e5f95bbbc",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Progressive Psy Trance Picks Vol.8",
              release_date: "2012-04-02",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:2pANdqPvxInB0YvcDiw4ko",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
                  },
                  href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                  id: "0LyfQWJT6nXafLPZqxe9Of",
                  name: "Çeşitli Sanatçılar",
                  type: "artist",
                  uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/6eSdhw46riw2OUHgMwR8B5",
                },
                href: "https://api.spotify.com/v1/artists/6eSdhw46riw2OUHgMwR8B5",
                id: "6eSdhw46riw2OUHgMwR8B5",
                name: "Odiseo",
                type: "artist",
                uri: "spotify:artist:6eSdhw46riw2OUHgMwR8B5",
              },
            ],
            available_markets: [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK",
            ],
            disc_number: 1,
            duration_ms: 376000,
            explicit: false,
            external_ids: { isrc: "DEKC41200989" },
            external_urls: {
              spotify: "https://open.spotify.com/track/4rzfv0JLZfVhOhbSQ8o5jZ",
            },
            href: "https://api.spotify.com/v1/tracks/4rzfv0JLZfVhOhbSQ8o5jZ",
            id: "4rzfv0JLZfVhOhbSQ8o5jZ",
            name: "Api",
            popularity: 0,
            preview_url: null,
            track_number: 10,
            type: "track",
            uri: "spotify:track:4rzfv0JLZfVhOhbSQ8o5jZ",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,

          video_thumbnail: {
            url: null,
          },
        },
        {
          added_at: "2015-01-15T12:40:03Z",
          added_by: {
            external_urls: {
              spotify: "https://open.spotify.com/user/jmperezperez",
            },
            href: "https://api.spotify.com/v1/users/jmperezperez",
            id: "jmperezperez",
            type: "user",
            uri: "spotify:user:jmperezperez",
          },
          is_local: false,
          track: {
            album: {
              album_type: "compilation",
              total_tracks: 25,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/6nlfkk5GoXRL1nktlATNsy",
              },
              href: "https://api.spotify.com/v1/albums/6nlfkk5GoXRL1nktlATNsy",
              id: "6nlfkk5GoXRL1nktlATNsy",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273aa2ff29970d9a63a49dfaeb2",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02aa2ff29970d9a63a49dfaeb2",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851aa2ff29970d9a63a49dfaeb2",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Wellness & Dreaming Source",
              release_date: "2015-01-09",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:6nlfkk5GoXRL1nktlATNsy",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
                  },
                  href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                  id: "0LyfQWJT6nXafLPZqxe9Of",
                  name: "Çeşitli Sanatçılar",
                  type: "artist",
                  uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5VQE4WOzPu9h3HnGLuBoA6",
                },
                href: "https://api.spotify.com/v1/artists/5VQE4WOzPu9h3HnGLuBoA6",
                id: "5VQE4WOzPu9h3HnGLuBoA6",
                name: "Vlasta Marek",
                type: "artist",
                uri: "spotify:artist:5VQE4WOzPu9h3HnGLuBoA6",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 730066,
            explicit: false,
            external_ids: { isrc: "FR2X41475057" },
            external_urls: {
              spotify: "https://open.spotify.com/track/5o3jMYOSbaVz3tkgwhELSV",
            },
            href: "https://api.spotify.com/v1/tracks/5o3jMYOSbaVz3tkgwhELSV",
            id: "5o3jMYOSbaVz3tkgwhELSV",
            name: "Is",
            popularity: 0,
            preview_url: null,
            track_number: 21,
            type: "track",
            uri: "spotify:track:5o3jMYOSbaVz3tkgwhELSV",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,

          video_thumbnail: {
            url: null,
          },
        },
        {
          added_at: "2015-01-15T12:22:30Z",
          added_by: {
            external_urls: {
              spotify: "https://open.spotify.com/user/jmperezperez",
            },
            href: "https://api.spotify.com/v1/users/jmperezperez",
            id: "jmperezperez",
            type: "user",
            uri: "spotify:user:jmperezperez",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 9,
              available_markets: [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
              ],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/4hnqM0JK4CM1phwfq1Ldyz",
              },
              href: "https://api.spotify.com/v1/albums/4hnqM0JK4CM1phwfq1Ldyz",
              id: "4hnqM0JK4CM1phwfq1Ldyz",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273ee0d0dce888c6c8a70db6e8b",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02ee0d0dce888c6c8a70db6e8b",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851ee0d0dce888c6c8a70db6e8b",
                  height: 64,
                  width: 64,
                },
              ],
              name: "This Is Happening",
              release_date: "2010-05-17",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:4hnqM0JK4CM1phwfq1Ldyz",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6",
                  },
                  href: "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
                  id: "066X20Nz7iquqkkCW6Jxy6",
                  name: "LCD Soundsystem",
                  type: "artist",
                  uri: "spotify:artist:066X20Nz7iquqkkCW6Jxy6",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6",
                },
                href: "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
                id: "066X20Nz7iquqkkCW6Jxy6",
                name: "LCD Soundsystem",
                type: "artist",
                uri: "spotify:artist:066X20Nz7iquqkkCW6Jxy6",
              },
            ],
            available_markets: [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK",
            ],
            disc_number: 1,
            duration_ms: 401440,
            explicit: false,
            external_ids: { isrc: "US4GE1000022" },
            external_urls: {
              spotify: "https://open.spotify.com/track/4Cy0NHJ8Gh0xMdwyM9RkQm",
            },
            href: "https://api.spotify.com/v1/tracks/4Cy0NHJ8Gh0xMdwyM9RkQm",
            id: "4Cy0NHJ8Gh0xMdwyM9RkQm",
            name: "All I Want",
            popularity: 39,
            preview_url: null,
            track_number: 4,
            type: "track",
            uri: "spotify:track:4Cy0NHJ8Gh0xMdwyM9RkQm",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,

          video_thumbnail: {
            url: null,
          },
        },
        {
          added_at: "2015-01-15T12:40:35Z",
          added_by: {
            external_urls: {
              spotify: "https://open.spotify.com/user/jmperezperez",
            },
            href: "https://api.spotify.com/v1/users/jmperezperez",
            id: "jmperezperez",
            type: "user",
            uri: "spotify:user:jmperezperez",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 8,
              available_markets: [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
              ],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/2usKFntxa98WHMcyW6xJBz",
              },
              href: "https://api.spotify.com/v1/albums/2usKFntxa98WHMcyW6xJBz",
              id: "2usKFntxa98WHMcyW6xJBz",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b2738b7447ac3daa1da18811cf7b",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e028b7447ac3daa1da18811cf7b",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d000048518b7447ac3daa1da18811cf7b",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Glenn Horiuchi Trio / Gelenn Horiuchi Quartet: Mercy / Jump Start / Endpoints / Curl Out / Earthworks / Mind Probe / Null Set / Another Space (A)",
              release_date: "2011-04-01",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:2usKFntxa98WHMcyW6xJBz",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/272ArH9SUAlslQqsSgPJA2",
                  },
                  href: "https://api.spotify.com/v1/artists/272ArH9SUAlslQqsSgPJA2",
                  id: "272ArH9SUAlslQqsSgPJA2",
                  name: "Glenn Horiuchi Trio",
                  type: "artist",
                  uri: "spotify:artist:272ArH9SUAlslQqsSgPJA2",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/272ArH9SUAlslQqsSgPJA2",
                },
                href: "https://api.spotify.com/v1/artists/272ArH9SUAlslQqsSgPJA2",
                id: "272ArH9SUAlslQqsSgPJA2",
                name: "Glenn Horiuchi Trio",
                type: "artist",
                uri: "spotify:artist:272ArH9SUAlslQqsSgPJA2",
              },
            ],
            available_markets: [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK",
            ],
            disc_number: 1,
            duration_ms: 358760,
            explicit: false,
            external_ids: { isrc: "USB8U1025969" },
            external_urls: {
              spotify: "https://open.spotify.com/track/6hvFrZNocdt2FcKGCSY5NI",
            },
            href: "https://api.spotify.com/v1/tracks/6hvFrZNocdt2FcKGCSY5NI",
            id: "6hvFrZNocdt2FcKGCSY5NI",
            name: "Endpoints",
            popularity: 0,
            preview_url: null,
            track_number: 2,
            type: "track",
            uri: "spotify:track:6hvFrZNocdt2FcKGCSY5NI",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,

          video_thumbnail: {
            url: null,
          },
        },
        {
          added_at: "2015-01-15T12:41:10Z",
          added_by: {
            external_urls: {
              spotify: "https://open.spotify.com/user/jmperezperez",
            },
            href: "https://api.spotify.com/v1/users/jmperezperez",
            id: "jmperezperez",
            type: "user",
            uri: "spotify:user:jmperezperez",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 18,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/0ivM6kSawaug0j3tZVusG2",
              },
              href: "https://api.spotify.com/v1/albums/0ivM6kSawaug0j3tZVusG2",
              id: "0ivM6kSawaug0j3tZVusG2",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b27304e57d181ff062f8339d6c71",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e0204e57d181ff062f8339d6c71",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d0000485104e57d181ff062f8339d6c71",
                  height: 64,
                  width: 64,
                },
              ],
              name: "All The Best (Spanish Version)",
              release_date: "2007-01-01",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:0ivM6kSawaug0j3tZVusG2",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/2KftmGt9sk1yLjsAoloC3M",
                  },
                  href: "https://api.spotify.com/v1/artists/2KftmGt9sk1yLjsAoloC3M",
                  id: "2KftmGt9sk1yLjsAoloC3M",
                  name: "Zucchero",
                  type: "artist",
                  uri: "spotify:artist:2KftmGt9sk1yLjsAoloC3M",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2KftmGt9sk1yLjsAoloC3M",
                },
                href: "https://api.spotify.com/v1/artists/2KftmGt9sk1yLjsAoloC3M",
                id: "2KftmGt9sk1yLjsAoloC3M",
                name: "Zucchero",
                type: "artist",
                uri: "spotify:artist:2KftmGt9sk1yLjsAoloC3M",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 176093,
            explicit: false,
            external_ids: { isrc: "ITUM70701043" },
            external_urls: {
              spotify: "https://open.spotify.com/track/2E2znCPaS8anQe21GLxcvJ",
            },
            href: "https://api.spotify.com/v1/tracks/2E2znCPaS8anQe21GLxcvJ",
            id: "2E2znCPaS8anQe21GLxcvJ",
            name: "You Are So Beautiful",
            popularity: 0,
            preview_url: null,
            track_number: 18,
            type: "track",
            uri: "spotify:track:2E2znCPaS8anQe21GLxcvJ",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,

          video_thumbnail: {
            url: null,
          },
        },
      ],
      [
        {
          added_at: "2010-03-04T08:40:06Z",
          added_by: {
            external_urls: { spotify: "https://open.spotify.com/user/smedjan" },
            href: "https://api.spotify.com/v1/users/smedjan",
            id: "smedjan",
            type: "user",
            uri: "spotify:user:smedjan",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 13,
              available_markets: [
                "AR",
                "AU",
                "AT",
                "BO",
                "BR",
                "BG",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IT",
                "LV",
                "LT",
                "MY",
                "MT",
                "MX",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "AD",
                "LI",
                "MC",
                "ID",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "KN",
                "LC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
              ],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/7uec0BVjt7qzfw4jmtEgNy",
              },
              href: "https://api.spotify.com/v1/albums/7uec0BVjt7qzfw4jmtEgNy",
              id: "7uec0BVjt7qzfw4jmtEgNy",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273b42bb39529620f443fc95ec6",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02b42bb39529620f443fc95ec6",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851b42bb39529620f443fc95ec6",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Jazz In The City",
              release_date: "2007-01-01",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:7uec0BVjt7qzfw4jmtEgNy",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/0fvpn2k7FymYHxEx5U5FpP",
                  },
                  href: "https://api.spotify.com/v1/artists/0fvpn2k7FymYHxEx5U5FpP",
                  id: "0fvpn2k7FymYHxEx5U5FpP",
                  name: "Gare Du Nord",
                  type: "artist",
                  uri: "spotify:artist:0fvpn2k7FymYHxEx5U5FpP",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/3uO6HG2JwyP744sg4PMmg5",
                },
                href: "https://api.spotify.com/v1/artists/3uO6HG2JwyP744sg4PMmg5",
                id: "3uO6HG2JwyP744sg4PMmg5",
                name: "Bobby Hutcherson",
                type: "artist",
                uri: "spotify:artist:3uO6HG2JwyP744sg4PMmg5",
              },
            ],
            available_markets: [
              "AR",
              "AU",
              "AT",
              "BO",
              "BR",
              "BG",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IT",
              "LV",
              "LT",
              "MY",
              "MT",
              "MX",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "AD",
              "LI",
              "MC",
              "ID",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "KN",
              "LC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK",
            ],
            disc_number: 1,
            duration_ms: 264093,
            explicit: false,
            external_ids: { isrc: "USBN29801531" },
            external_urls: {
              spotify: "https://open.spotify.com/track/6SdkKrqkPUlzJf0AdRyxSt",
            },
            href: "https://api.spotify.com/v1/tracks/6SdkKrqkPUlzJf0AdRyxSt",
            id: "6SdkKrqkPUlzJf0AdRyxSt",
            name: "Montara",
            popularity: 1,
            preview_url: null,
            track_number: 10,
            type: "track",
            uri: "spotify:track:6SdkKrqkPUlzJf0AdRyxSt",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,
          video_thumbnail: { url: null },
        },
        {
          added_at: "2010-03-09T20:09:28Z",
          added_by: {
            external_urls: { spotify: "https://open.spotify.com/user/" },
            href: "https://api.spotify.com/v1/users/",
            id: "",
            type: "user",
            uri: "spotify:user:",
          },
          is_local: false,
          track: {
            album: {
              album_type: "single",
              total_tracks: 4,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/6jhQBrBEdCxHCfnZmgeT7t",
              },
              href: "https://api.spotify.com/v1/albums/6jhQBrBEdCxHCfnZmgeT7t",
              id: "6jhQBrBEdCxHCfnZmgeT7t",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b27333c4ba278bdf1f0a5c08690c",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e0233c4ba278bdf1f0a5c08690c",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d0000485133c4ba278bdf1f0a5c08690c",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Analogue Bubblebath - EP",
              release_date: "1994-02-22",
              release_date_precision: "day",
              type: "album",
              uri: "spotify:album:6jhQBrBEdCxHCfnZmgeT7t",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/6ULjGlnhcCwHIJigN47K5U",
                  },
                  href: "https://api.spotify.com/v1/artists/6ULjGlnhcCwHIJigN47K5U",
                  id: "6ULjGlnhcCwHIJigN47K5U",
                  name: "AFX",
                  type: "artist",
                  uri: "spotify:artist:6ULjGlnhcCwHIJigN47K5U",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/6ULjGlnhcCwHIJigN47K5U",
                },
                href: "https://api.spotify.com/v1/artists/6ULjGlnhcCwHIJigN47K5U",
                id: "6ULjGlnhcCwHIJigN47K5U",
                name: "AFX",
                type: "artist",
                uri: "spotify:artist:6ULjGlnhcCwHIJigN47K5U",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 326440,
            explicit: false,
            external_ids: { isrc: "USTV19400123" },
            external_urls: {
              spotify: "https://open.spotify.com/track/78ZHugVlzEzw9WyBVPQl2s",
            },
            href: "https://api.spotify.com/v1/tracks/78ZHugVlzEzw9WyBVPQl2s",
            id: "78ZHugVlzEzw9WyBVPQl2s",
            name: "Afx 2",
            popularity: 0,
            preview_url: null,
            track_number: 4,
            type: "track",
            uri: "spotify:track:78ZHugVlzEzw9WyBVPQl2s",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,
          video_thumbnail: { url: null },
        },
        {
          added_at: "2010-03-16T15:09:18Z",
          added_by: {
            external_urls: { spotify: "https://open.spotify.com/user/" },
            href: "https://api.spotify.com/v1/users/",
            id: "",
            type: "user",
            uri: "spotify:user:",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 16,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/3E8ddTU9rejbDnn4k8hJ3b",
              },
              href: "https://api.spotify.com/v1/albums/3E8ddTU9rejbDnn4k8hJ3b",
              id: "3E8ddTU9rejbDnn4k8hJ3b",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273b36d6d41fa97a2c52bb60943",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02b36d6d41fa97a2c52bb60943",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851b36d6d41fa97a2c52bb60943",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Soundtrack",
              release_date: "2007",
              release_date_precision: "year",
              type: "album",
              uri: "spotify:album:3E8ddTU9rejbDnn4k8hJ3b",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                  },
                  href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                  id: "2bK3Mw0UFdqaErrATXS0bN",
                  name: "Young@Heart Chorus",
                  type: "artist",
                  uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                },
                href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                id: "2bK3Mw0UFdqaErrATXS0bN",
                name: "Young@Heart Chorus",
                type: "artist",
                uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 146933,
            explicit: false,
            external_ids: { isrc: "USRH10801865" },
            external_urls: {
              spotify: "https://open.spotify.com/track/4NptYvhW8KierhPWKz7kHF",
            },
            href: "https://api.spotify.com/v1/tracks/4NptYvhW8KierhPWKz7kHF",
            id: "4NptYvhW8KierhPWKz7kHF",
            name: "Should I Stay Or Should I Go [Soundtrack Version]",
            popularity: 0,
            preview_url: null,
            track_number: 1,
            type: "track",
            uri: "spotify:track:4NptYvhW8KierhPWKz7kHF",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,
          video_thumbnail: { url: null },
        },
        {
          added_at: "2010-03-16T15:09:18Z",
          added_by: {
            external_urls: { spotify: "https://open.spotify.com/user/" },
            href: "https://api.spotify.com/v1/users/",
            id: "",
            type: "user",
            uri: "spotify:user:",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 16,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/3E8ddTU9rejbDnn4k8hJ3b",
              },
              href: "https://api.spotify.com/v1/albums/3E8ddTU9rejbDnn4k8hJ3b",
              id: "3E8ddTU9rejbDnn4k8hJ3b",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273b36d6d41fa97a2c52bb60943",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02b36d6d41fa97a2c52bb60943",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851b36d6d41fa97a2c52bb60943",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Soundtrack",
              release_date: "2007",
              release_date_precision: "year",
              type: "album",
              uri: "spotify:album:3E8ddTU9rejbDnn4k8hJ3b",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                  },
                  href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                  id: "2bK3Mw0UFdqaErrATXS0bN",
                  name: "Young@Heart Chorus",
                  type: "artist",
                  uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                },
                href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                id: "2bK3Mw0UFdqaErrATXS0bN",
                name: "Young@Heart Chorus",
                type: "artist",
                uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 108346,
            explicit: false,
            external_ids: { isrc: "USRH10801866" },
            external_urls: {
              spotify: "https://open.spotify.com/track/3UuVaWQawvK9K5SOH4ZapU",
            },
            href: "https://api.spotify.com/v1/tracks/3UuVaWQawvK9K5SOH4ZapU",
            id: "3UuVaWQawvK9K5SOH4ZapU",
            name: "I Wanna Be Sedated [Soundtrack Version]",
            popularity: 0,
            preview_url: null,
            track_number: 2,
            type: "track",
            uri: "spotify:track:3UuVaWQawvK9K5SOH4ZapU",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,
          video_thumbnail: { url: null },
        },
        {
          added_at: "2010-03-16T15:09:18Z",
          added_by: {
            external_urls: { spotify: "https://open.spotify.com/user/" },
            href: "https://api.spotify.com/v1/users/",
            id: "",
            type: "user",
            uri: "spotify:user:",
          },
          is_local: false,
          track: {
            album: {
              album_type: "album",
              total_tracks: 16,
              available_markets: [],
              external_urls: {
                spotify:
                  "https://open.spotify.com/album/3E8ddTU9rejbDnn4k8hJ3b",
              },
              href: "https://api.spotify.com/v1/albums/3E8ddTU9rejbDnn4k8hJ3b",
              id: "3E8ddTU9rejbDnn4k8hJ3b",
              images: [
                {
                  url: "https://i.scdn.co/image/ab67616d0000b273b36d6d41fa97a2c52bb60943",
                  height: 640,
                  width: 640,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00001e02b36d6d41fa97a2c52bb60943",
                  height: 300,
                  width: 300,
                },
                {
                  url: "https://i.scdn.co/image/ab67616d00004851b36d6d41fa97a2c52bb60943",
                  height: 64,
                  width: 64,
                },
              ],
              name: "Soundtrack",
              release_date: "2007",
              release_date_precision: "year",
              type: "album",
              uri: "spotify:album:3E8ddTU9rejbDnn4k8hJ3b",
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                  },
                  href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                  id: "2bK3Mw0UFdqaErrATXS0bN",
                  name: "Young@Heart Chorus",
                  type: "artist",
                  uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
                },
              ],
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2bK3Mw0UFdqaErrATXS0bN",
                },
                href: "https://api.spotify.com/v1/artists/2bK3Mw0UFdqaErrATXS0bN",
                id: "2bK3Mw0UFdqaErrATXS0bN",
                name: "Young@Heart Chorus",
                type: "artist",
                uri: "spotify:artist:2bK3Mw0UFdqaErrATXS0bN",
              },
            ],
            available_markets: [],
            disc_number: 1,
            duration_ms: 88506,
            explicit: false,
            external_ids: { isrc: "USRH10801867" },
            external_urls: {
              spotify: "https://open.spotify.com/track/0qdLAuvTvJz2nV1PPe7tO8",
            },
            href: "https://api.spotify.com/v1/tracks/0qdLAuvTvJz2nV1PPe7tO8",
            id: "0qdLAuvTvJz2nV1PPe7tO8",
            name: "Every Breath You Take [Soundtrack Version]",
            popularity: 0,
            preview_url: null,
            track_number: 3,
            type: "track",
            uri: "spotify:track:0qdLAuvTvJz2nV1PPe7tO8",
            is_local: false,
            episode: false,
            track: true,
          },
          primary_color: null,
          video_thumbnail: { url: null },
        },
      ],
    ],
  },
};
